import { Metadata } from "next"
import ZundamonQuestionForm from "../components/ZundamonQuestionForm"

export const metadata = {
  title: 'Top page.',
  description: 'Generated by Next.js',
} satisfies Metadata

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <ZundamonQuestionForm />
        {children}
      </body>
    </html>
  )
}
