import { Metadata } from "next"

export const metadata = {
  title: 'Top page.',
  description: 'Generated by Next.js',
} satisfies Metadata

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  )
}
